---
all:
  vars:
    ansible_user: admin
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_become: yes
    ansible_become_method: sudo

  children:
    linux_servers:
      hosts:
        srv-linux:
          ansible_host: 10.0.100.10
        srv-wazuh:
          ansible_host: 10.0.100.20
        srv-monitoring:
          ansible_host: 10.0.100.30
        srv-suricata:
          ansible_host: 10.0.100.40

    dns_servers:
      hosts:
        srv-linux:

    web_servers:
      hosts:
        srv-linux:

    proxy_servers:
      hosts:
        srv-linux:

    siem_servers:
      hosts:
        srv-wazuh:

    monitoring_servers:
      hosts:
        srv-monitoring:

    ids_servers:
      hosts:
        srv-suricata:
